/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Parse a `.px` source and check **every** `constraint` in it against a JSON
 * variable map. Returns a JSON array of outcomes.
 *
 * Each element is `{ "name": <constraint name>, "status": "satisfied" |
 * "violated" | "not_applicable", "severity"?: "error"|"warning"|"info",
 * "message"?: <string> }`. Delegates to `px_eval::eval_constraint` (the real
 * constraint evaluator) using the pure function registry.
 *
 * Throws if the source fails to parse or `vars_json` is not a JSON object.
 */
export declare function checkConstraints(src: string, varsJson: string): string

/**
 * Evaluate a single v1 `.px` expression against a JSON variable map.
 *
 * `vars_json` must be a JSON object (`{"x": 10, "name": "abc"}`); its entries
 * become the evaluation context. Delegates to `px_eval::evaluate` (the real
 * evaluator) and returns the result value as a JSON string.
 *
 * Throws if `vars_json` is not a JSON object, or if the expression fails to
 * parse or evaluate.
 */
export declare function evaluate(expr: string, varsJson: string): string

/**
 * Parse a `.px` source string into the canonical AST, returned as JSON.
 *
 * Delegates to `px_compiler::parse` (the real front end) and serializes the
 * resulting [`px_ast::PxDocument`] with `serde_json`. The JSON uses the same
 * kind-tagged encoding as the rest of the toolchain, so a TS consumer sees the
 * exact canonical AST shape.
 *
 * Throws (JS `Error`) if the source does not parse.
 */
export declare function parse(src: string): string

/** The `px-ast` crate version this addon was built against. */
export declare function pxAstVersion(): string
